### ISSUE TITLE
Do slaves need update-center.json?

### ISSUE THREAD

**Issue by FreakyDug** [chef-cookbooks/jenkins#463] opened 2016-04-06 10:35 UTC
I am trying to use the Jenkins cookbook to configure slaves on a subnet which does not have internet access. During the slave set up process the cookbook downloads update-center.json from the jenkins mirror site, which means its something I need to provide an local source for. (The master is on a different subnet which does have internet access so it can download it fine)

Is there some reason I'm missing for having it or is it just the slave resource reusing a function designed for the master?

**Comment by iennae** [comment] 2016-10-10 07:01
@FreakyDug Thanks for reporting this issue. I've done some brief research and will target coming up with a solution for this next week. It might not get resolved in that time, but I hope to have a plan to help resolve it. If you've already figured out a mechanism to resolve this in your own environment, please do share and I can potentially add your fix to the cookbook.

Thanks!

**Comment by FreakyDug** [comment] 2016-10-10 09:56
@iennae I didn't find a real fix, I just put a copy of update-center.json on a local web server and pointed the cookbook at that via default['jenkins']['master']['mirror'] (on the non-internet agents). The file is now out of date, but as far as I can tell, the agent doesn't actually use it so it doesn't matter.

**Comment by iennae** [comment] 2016-10-25 13:01
Moving this out a little bit. Thanks for the update!

**Comment by cheeseplus** [comment] 2017-03-20 21:47
Closing this one as a dupe of https://github.com/chef-cookbooks/jenkins/issues/403 just to reduce some of the noise. I'll be working on the one this week.

**Closed by cheeseplus** 2017-03-20 21:47 UTC
Labels: Type: Bug
