### ISSUE TITLE
jenkins_plugin :install brute forces dependencies version?

### ISSUE THREAD

**Issue by varadharajan** [chef-cookbooks/jenkins#573] opened 2017-03-06 07:20 UTC
When we try to install a plugin with lot of dependencies, say 'workflow-aggregator' for example, the jenkins_plugin :install step takes a lot of time in comparison with Jenkins CLI install-plugin command. I guess it downloads multiple versions and then tries to figure out the compatibility? 

For example, this is how my cache directory looks like after installing workflow-aggregator, version: 2.5

```ruby
jenkins_plugin "workflow-aggregator" do
  version '2.5'
  action :install
end
```

```
ace-editor-1.0.1.plugin
branch-api-2.0.7.plugin
chef-client-running.pid
chef-stacktrace.out
cloudbees-folder-5.12.plugin
cloudbees-folder-5.17.plugin
cloudbees-folder-5.18.plugin
cookbooks
credentials-2.1.13.plugin
display-url-api-1.0.plugin
durable-task-1.13.plugin
extracted-update-center.json
git-client-1.11.0.plugin
git-client-1.19.7.plugin
git-server-1.5.plugin
handlebars-1.1.plugin
jenkins-cli.jar
jenkins-key
jquery-detached-1.2.1.plugin
junit-1.19.plugin
mailer-1.13.plugin
momentjs-1.1.plugin
pipeline-graph-analysis-1.1.plugin
pipeline-input-step-2.0.plugin
pipeline-input-step-2.5.plugin
pipeline-rest-api-2.5.plugin
pipeline-stage-step-2.2.plugin
pipeline-stage-view-2.4.plugin
remote_file
scm-api-1.3.plugin
scm-api-2.0.2.plugin
scm-api-2.0.7.plugin
script-security-1.21.plugin
script-security-1.23.plugin
script-security-1.25.plugin
script-security-1.26.plugin
ssh-credentials-1.12.plugin
structs-1.2.plugin
structs-1.4.plugin
structs-1.5.plugin
structs-1.6.plugin
update-center.json
workflow-api-1.15.plugin
workflow-api-2.11.plugin
workflow-api-2.2.plugin
workflow-api-2.3.plugin
workflow-api-2.4.plugin
workflow-api-2.5.plugin
workflow-api-2.6.plugin
workflow-api-2.8.plugin
workflow-basic-steps-2.3.plugin
workflow-cps-2.19.plugin
workflow-cps-2.23.plugin
workflow-cps-2.24.plugin
workflow-cps-2.28.plugin
workflow-cps-2.2.plugin
workflow-cps-global-lib-2.5.plugin
workflow-durable-task-step-2.5.plugin
workflow-durable-task-step-2.8.plugin
workflow-job-2.0.plugin
workflow-job-2.10.plugin
workflow-job-2.9.plugin
workflow-multibranch-2.9.2.plugin
workflow-scm-step-2.2.plugin
workflow-scm-step-2.3.plugin
workflow-scm-step-2.4.plugin
workflow-step-api-1.15.plugin
workflow-step-api-2.1.plugin
workflow-step-api-2.4.plugin
workflow-step-api-2.5.plugin
workflow-step-api-2.7.plugin
workflow-step-api-2.9.plugin
workflow-support-2.10.plugin
workflow-support-2.12.plugin
workflow-support-2.13.plugin
workflow-support-2.1.plugin
workflow-support-2.2.plugin

```

Is there a way to use the Jenkins CLI install-plugin directly?

**Comment by cheeseplus** [comment] 2017-03-07 21:08
Closing as dupe of https://github.com/chef-cookbooks/jenkins/issues/573

**Closed by cheeseplus** 2017-03-07 21:08 UTC
