### ISSUE TITLE
Plugin installation fails 

### ISSUE THREAD

**Issue by endejoli** [chef-cookbooks/jenkins#485] opened 2016-06-12 20:20 UTC
### Cookbook version

2.5.0
### Chef-client version

Chef: 12.7.2
### Platform Details

Ubuntu 14.04
### Scenario:

I am Trying to install plugins to  jenkins version '1.651.2'

recipe: 

jenkins_plugin 'ldap' do
 version '1.12'
end

kitchen converge gets stuck  at :

```
* jenkins_plugin[ldap] action install
     Recipe: <Dynamically Defined Resource>
       * remote_file[/tmp/kitchen/cache/update-center.json] action create
         - create new file /tmp/kitchen/cache/update-center.json
         - update content in file /tmp/kitchen/cache/update-center.json from none to 7beb57
         - suppressed sensitive resource
         - change mode from '' to '0644'
       * file[/tmp/kitchen/cache/extracted-update-center.json] action create
         - create new file /tmp/kitchen/cache/extracted-update-center.json
         - update content in file /tmp/kitchen/cache/extracted-update-center.json from none to a3c365
         - suppressed sensitive resource
         - change mode from '' to '0644'
```
### Steps to Reproduce:

jenkins_plugin 'ldap' do
 version '1.12'
end
### Expected Result:

Plugin should get installed successfully 
### Actual Result:

 Execution gets stuck

**Comment by tas50** [comment] 2017-01-17 18:52
Closing as a dupe of #534

**Closed by tas50** 2017-01-17 18:52 UTC
