### ISSUE TITLE
Does not work with Chef 13

### ISSUE THREAD

**Issue by scarolan** [chef-cookbooks/jenkins#634] opened 2017-06-29 14:09 UTC
### Cookbook version
5.0.2

### Chef-client version
13.x

### Platform Details
Centos 7 on Vagrant

### Scenario:
Run default recipe, fails.  Switch to chef 12 and it works.

### Steps to Reproduce:
Just use the included kitchen.yml and watch it fail.

### Expected Result:
Jenkins should be installed and started

### Actual Result:
Chef run fails, kitchen fails

**Comment by tas50** [comment] 2017-07-04 18:55
@scarolan I'm trying to reproduce this and I'm not seeing issues with Chef 13. Can you give it a try with the latest releases and get back to me with more information.

**Comment by oberones** [comment] 2017-11-16 14:51
This is still an issue. Specifically, you can not connect a slave via jnlp or ssh connection method under Chef 13. There is an open issue regarding the specific error that is returned here:

https://github.com/chef-cookbooks/jenkins/issues/615

I have attached the output from my converge attempt as well as the resulting stacktrace on that thread.

**Comment by tas50** [comment] 2017-11-23 00:00
This has been fixed on master and I'll be cutting a release once I fix a few other problems

**Closed** 2017-11-23 00:00 UTC

**Comment by damacus** [comment] 2026-01-13 14:01
Closing this issue as stale. It was opened in 2018 and the cookbook has undergone significant changes since then. If this is still a problem with the current version of the cookbook, please open a new issue with updated details.

**Comment by scarolan** [comment] 2026-01-13 18:13
holy shit Chef still exists? 🤯
