### ISSUE TITLE
jenkins_plugin fails for git* plugins

### ISSUE THREAD

**Issue by lioramilbaum** [chef-cookbooks/jenkins#551] opened 2017-01-17 06:05 UTC
### Cookbook version
4.1.2

### Chef-client version
12.17.44-1

### Platform Details

AWS Ubuntu 16.04

### Scenario:

installing Jenkins github (git, git-parameter) plugin 

jenkins_plugin 'github' do
      version "1.25.1"
end

plugin scm-api version 2.0.1 already installed.

### Expected Result:

github plugin and its dependencies are installed while avoiding installing whatever depended plugins which are already installed

### Actual Result:
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com   * jenkins_plugin[github] action install
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com   Recipe: <Dynamically Defined Resource>
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com     * remote_file[/var/chef/cache/structs-1.5.plugin] action create
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       - create new file /var/chef/cache/structs-1.5.plugin
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       - update content in file /var/chef/cache/structs-1.5.plugin from none to 5a739b
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       (new content is binary, diff output suppressed)
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com     * remote_file[/var/chef/cache/workflow-step-api-1.15.plugin] action create
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       - create new file /var/chef/cache/workflow-step-api-1.15.plugin
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       - update content in file /var/chef/cache/workflow-step-api-1.15.plugin from none to ac3bdd
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       (new content is binary, diff output suppressed)
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com     * remote_file[/var/chef/cache/workflow-scm-step-1.14.2.plugin] action create
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       - create new file /var/chef/cache/workflow-scm-step-1.14.2.plugin
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       - update content in file /var/chef/cache/workflow-scm-step-1.14.2.plugin from none to fc4589
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       (new content is binary, diff output suppressed)
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com     * remote_file[/var/chef/cache/ssh-credentials-1.12.plugin] action create
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       - create new file /var/chef/cache/ssh-credentials-1.12.plugin
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       - update content in file /var/chef/cache/ssh-credentials-1.12.plugin from none to 999fb0
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       (new content is binary, diff output suppressed)
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com     * remote_file[/var/chef/cache/structs-1.5.plugin] action create (up to date)
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com     * remote_file[/var/chef/cache/git-client-2.1.0.plugin] action create
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       - create new file /var/chef/cache/git-client-2.1.0.plugin
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       - update content in file /var/chef/cache/git-client-2.1.0.plugin from none to 8113fa
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       (new content is binary, diff output suppressed)
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com     * remote_file[/var/chef/cache/structs-1.2.plugin] action create (up to date)
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com     * remote_file[/var/chef/cache/junit-1.3.plugin] action create
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       - create new file /var/chef/cache/junit-1.3.plugin
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       - update content in file /var/chef/cache/junit-1.3.plugin from none to 6b8172
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       (new content is binary, diff output suppressed)
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com     * remote_file[/var/chef/cache/display-url-api-0.2.plugin] action create
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       - create new file /var/chef/cache/display-url-api-0.2.plugin
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       - update content in file /var/chef/cache/display-url-api-0.2.plugin from none to f80f09
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       (new content is binary, diff output suppressed)
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com     * remote_file[/var/chef/cache/mailer-1.18.plugin] action create
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       - create new file /var/chef/cache/mailer-1.18.plugin
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       - update content in file /var/chef/cache/mailer-1.18.plugin from none to 96a619
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       (new content is binary, diff output suppressed)
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com     * remote_file[/var/chef/cache/structs-1.2.plugin] action create (up to date)
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com     * remote_file[/var/chef/cache/junit-1.2.plugin] action create
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       - update content in file /var/chef/cache/junit-1.2.plugin from 3d2886 to 6b8172
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       (current file is binary, diff output suppressed)
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com     * remote_file[/var/chef/cache/script-security-1.13.plugin] action create (up to date)
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com     * remote_file[/var/chef/cache/matrix-project-1.7.1.plugin] action create
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       - create new file /var/chef/cache/matrix-project-1.7.1.plugin
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       - update content in file /var/chef/cache/matrix-project-1.7.1.plugin from none to 16e574
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       (new content is binary, diff output suppressed)
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com     * remote_file[/var/chef/cache/scm-api-2.0.1.pre.beta.pre.1.plugin] action create[2017-01-17T05:42:53+00:00] WARN: remote_file[/var/chef/cache/scm-api-2.0.1.pre.beta.pre.1.plugin] cannot be downloaded from http://updates.jenkins-ci.org/download/plugins/scm-api/2.0.1.pre.beta.pre.1/scm-api.hpi: 404 "Not Found"
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com 
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       ================================================================================
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       Error executing action `create` on resource 'remote_file[/var/chef/cache/scm-api-2.0.1.pre.beta.pre.1.plugin]'
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       ================================================================================
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       Net::HTTPServerException
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       ------------------------
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       404 "Not Found"
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       Cookbook Trace:
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       ---------------
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       /var/chef/cache/cookbooks/jenkins/libraries/plugin.rb:310:in `install_plugin_from_url'
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       /var/chef/cache/cookbooks/jenkins/libraries/plugin.rb:288:in `install_plugin_from_update_center'
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       /var/chef/cache/cookbooks/jenkins/libraries/plugin.rb:279:in `block in install_plugin_from_update_center'
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       /var/chef/cache/cookbooks/jenkins/libraries/plugin.rb:272:in `each'
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       /var/chef/cache/cookbooks/jenkins/libraries/plugin.rb:272:in `install_plugin_from_update_center'
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       /var/chef/cache/cookbooks/jenkins/libraries/plugin.rb:279:in `block in install_plugin_from_update_center'
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       /var/chef/cache/cookbooks/jenkins/libraries/plugin.rb:272:in `each'
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       /var/chef/cache/cookbooks/jenkins/libraries/plugin.rb:272:in `install_plugin_from_update_center'
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       /var/chef/cache/cookbooks/jenkins/libraries/plugin.rb:123:in `block (2 levels) in <class:JenkinsPlugin>'
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       /var/chef/cache/cookbooks/jenkins/libraries/plugin.rb:153:in `block in <class:JenkinsPlugin>'
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       Compiled Resource:
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       ------------------
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       # Declared in 
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       remote_file("/var/chef/cache/scm-api-2.0.1.pre.beta.pre.1.plugin") do
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com         provider Chef::Provider::RemoteFile
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com         action [:create]
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com         retries 0
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com         retry_delay 2
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com         default_guard_interpreter :default
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com         source ["http://updates.jenkins-ci.org/download/plugins/scm-api/2.0.1.pre.beta.pre.1/scm-api.hpi"]
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com         use_etag true
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com         use_last_modified true
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com         path "/var/chef/cache/scm-api-2.0.1.pre.beta.pre.1.plugin"
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       end
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       Platform:
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       ---------
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       x86_64-linux
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com     
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com     ================================================================================
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com     Error executing action `install` on resource 'jenkins_plugin[github]'
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com     ================================================================================
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com     
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com     Net::HTTPServerException
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com     ------------------------
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com     remote_file[/var/chef/cache/scm-api-2.0.1.pre.beta.pre.1.plugin] (dynamically defined) had an error: Net::HTTPServerException: 404 "Not Found"
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com     
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com     Cookbook Trace:
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com     ---------------
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com     /var/chef/cache/cookbooks/jenkins/libraries/plugin.rb:310:in `install_plugin_from_url'
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com     /var/chef/cache/cookbooks/jenkins/libraries/plugin.rb:288:in `install_plugin_from_update_center'
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com     /var/chef/cache/cookbooks/jenkins/libraries/plugin.rb:279:in `block in install_plugin_from_update_center'
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com     /var/chef/cache/cookbooks/jenkins/libraries/plugin.rb:272:in `each'
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com     /var/chef/cache/cookbooks/jenkins/libraries/plugin.rb:272:in `install_plugin_from_update_center'
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com     /var/chef/cache/cookbooks/jenkins/libraries/plugin.rb:279:in `block in install_plugin_from_update_center'
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com     /var/chef/cache/cookbooks/jenkins/libraries/plugin.rb:272:in `each'
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com     /var/chef/cache/cookbooks/jenkins/libraries/plugin.rb:272:in `install_plugin_from_update_center'
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com     /var/chef/cache/cookbooks/jenkins/libraries/plugin.rb:123:in `block (2 levels) in <class:JenkinsPlugin>'
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com     /var/chef/cache/cookbooks/jenkins/libraries/plugin.rb:153:in `block in <class:JenkinsPlugin>'
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com     
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com     Resource Declaration:
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com     ---------------------
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com     # In /var/chef/cache/cookbooks/lmb-jenkins/recipes/master.rb
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com     
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com      78:     jenkins_plugin p['name'] do
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com      79:       version p['version']
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com      80:       notifies :execute, "jenkins_command[safe-restart]", :immediately if index == node['jenkins']['my_plugins'].length - 1
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com      81:     end
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com      82: end
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com     
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com     Compiled Resource:
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com     ------------------
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com     # Declared in /var/chef/cache/cookbooks/lmb-jenkins/recipes/master.rb:78:in `block in from_file'
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com     
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com     jenkins_plugin("github") do
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       action [:install]
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       retries 0
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       retry_delay 2
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       default_guard_interpreter :default
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       declared_type :jenkins_plugin
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       cookbook_name "lmb-jenkins"
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       recipe_name "master"
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com       version "1.25.1"
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com     end
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com     
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com     Platform:
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com     ---------
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com     x86_64-linux
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com     
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com Recipe: jenkins::_master_war
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com   * runit_service[jenkins] action restart (up to date)
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com Recipe: iptables::default
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com   * execute[rebuild-iptables] action run
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com     - execute /usr/sbin/rebuild-iptables
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com 
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com Running handlers:
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com [2017-01-17T05:42:54+00:00] ERROR: Running exception handlers
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com Running handlers complete
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com [2017-01-17T05:42:54+00:00] ERROR: Exception handlers complete
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com Chef Client failed. 93 resources updated in 03 minutes 19 seconds
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com [2017-01-17T05:42:55+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com [2017-01-17T05:42:55+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com [2017-01-17T05:42:55+00:00] ERROR: jenkins_plugin[github] (lmb-jenkins::master line 78) had an error: Net::HTTPServerException: remote_file[/var/chef/cache/scm-api-2.0.1.pre.beta.pre.1.plugin] (dynamically defined) had an error: Net::HTTPServerException: 404 "Not Found"
ec2-52-31-5-114.eu-west-1.compute.amazonaws.com [2017-01-17T05:42:55+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
depi: 0:1

**Comment by tas50** [comment] 2017-01-17 18:51
Closing as this is a dupe of #534

**Closed by tas50** 2017-01-17 18:51 UTC
