### ISSUE TITLE
jenkins_jnlp_slave fails with undefined method

### ISSUE THREAD

**Issue by jmaass** [chef-cookbooks/jenkins#531] opened 2016-10-19 15:24 UTC
### Cookbook version

4.0.1
### Chef-client version

12.15.19
### Platform Details

Centos 7, 3.10.0-327.28.3.el7.x86_64
### Scenario:

Trying to install a Jenkins JNLP slave.
### Steps to Reproduce:

```
jenkins_jnlp_slave ipaddress do
  remote_fs '/home/jenkins'
  action [:create, :connect]
  not_if { master == 'localhost' }
end
```
### Expected Result:

The Jenkins JNLP slave is set up.
### Actual Result:

```

           ================================================================================
           Error executing action `create` on resource 'jenkins_jnlp_slave[192.168.211.251]'
           ================================================================================

           NoMethodError
           -------------
           undefined method `slave_jar_url' for Chef::Resource::RemoteFile

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/jenkins/libraries/slave_jnlp.rb:211:in `block in slave_jar_resource'
           /tmp/kitchen/cache/cookbooks/jenkins/libraries/slave_jnlp.rb:210:in `slave_jar_resource'
           /tmp/kitchen/cache/cookbooks/jenkins/libraries/slave_jnlp.rb:65:in `block in <class:JenkinsJnlpSlave>'

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/mnet_jenkins/recipes/slave.rb

            70: jenkins_jnlp_slave ipaddress do
            71:   remote_fs '/home/jenkins'
            72:   action [:create, :connect]
            73:   not_if { master == 'localhost' }
            74: end

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/mnet_jenkins/recipes/slave.rb:70:in `from_file'

           jenkins_jnlp_slave("192.168.211.251") do
             action [:create, :connect]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :jenkins_jnlp_slave
             cookbook_name "mnet_jenkins"
             recipe_name "slave"
             remote_fs "/home/jenkins"
             slave_name "192.168.211.251"
             usage_mode "normal"
             description "Jenkins slave 192.168.211.251"
             group "jenkins"
             user "jenkins"
             not_if { #code block }
           end

           Platform:
           ---------
           x86_64-linux

       Recipe: chef-client::systemd_service
         * service[chef-client] action restart
           - restart service service[chef-client]
       Recipe: misc::hosts_entry
         * service[network] action restart
           - restart service service[network]

       Running handlers:
       [2016-10-19T17:14:49+02:00] ERROR: Running exception handlers
       Running handlers complete
       [2016-10-19T17:14:49+02:00] ERROR: Exception handlers complete
       Chef Client failed. 57 resources updated in 43 seconds
       [2016-10-19T17:14:49+02:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2016-10-19T17:14:49+02:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2016-10-19T17:14:49+02:00] ERROR: jenkins_jnlp_slave[192.168.211.251] (mnet_jenkins::slave line 70) had an error: NoMethodError: undefined method `slave_jar_url' for Chef::Resource::RemoteFile
       [2016-10-19T17:14:50+02:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

Here's the stack.out:

```
-----> Execute command on jenkins-slave-centos07.
       Generated at 2016-10-19 17:14:49 +0200
       NoMethodError: jenkins_jnlp_slave[192.168.211.251] (mnet_jenkins::slave line 70) had an error: NoMethodError: undefined method `slave_jar_url' for Chef::Resource::RemoteFile
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/resource.rb:1347:in `method_missing'
       /tmp/kitchen/cache/cookbooks/jenkins/libraries/slave_jnlp.rb:211:in `block in slave_jar_resource'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/resource_builder.rb:76:in `instance_eval'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/resource_builder.rb:76:in `build'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/dsl/declare_resource.rb:285:in `build_resource'
       /tmp/kitchen/cache/cookbooks/jenkins/libraries/slave_jnlp.rb:210:in `slave_jar_resource'
       /tmp/kitchen/cache/cookbooks/jenkins/libraries/slave_jnlp.rb:65:in `block in <class:JenkinsJnlpSlave>'
       (eval):2:in `block in action_create'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/provider.rb:361:in `instance_eval'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/provider.rb:361:in `compile_and_converge_action'
       (eval):2:in `action_create'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/provider.rb:145:in `run_action'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/resource.rb:603:in `run_action'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/runner.rb:69:in `run_action'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/runner.rb:97:in `block (2 levels) in converge'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/runner.rb:97:in `each'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/runner.rb:97:in `block in converge'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/runner.rb:96:in `converge'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/client.rb:669:in `block in converge'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/client.rb:664:in `catch'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/client.rb:664:in `converge'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/client.rb:703:in `converge_and_save'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/client.rb:283:in `run'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/application.rb:302:in `block in fork_chef_client'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/application.rb:290:in `fork'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/application.rb:290:in `fork_chef_client'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/application.rb:255:in `block in run_chef_client'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/local_mode.rb:44:in `with_server_connectivity'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/application.rb:243:in `run_chef_client'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/application/client.rb:450:in `loop'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/application/client.rb:450:in `interval_run_chef_client'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/application/client.rb:434:in `run_application'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/application.rb:60:in `run'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/bin/chef-client:26:in `<top (required)>'
       /opt/chef/bin/chef-client:54:in `load'
       /opt/chef/bin/chef-client:54:in `<main>'

       >>>> Caused by NoMethodError: undefined method `slave_jar_url' for Chef::Resource::RemoteFile
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/resource.rb:1347:in `method_missing'
       /tmp/kitchen/cache/cookbooks/jenkins/libraries/slave_jnlp.rb:211:in `block in slave_jar_resource'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/resource_builder.rb:76:in `instance_eval'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/resource_builder.rb:76:in `build'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/dsl/declare_resource.rb:285:in `build_resource'
       /tmp/kitchen/cache/cookbooks/jenkins/libraries/slave_jnlp.rb:210:in `slave_jar_resource'
       /tmp/kitchen/cache/cookbooks/jenkins/libraries/slave_jnlp.rb:65:in `block in <class:JenkinsJnlpSlave>'
       (eval):2:in `block in action_create'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/provider.rb:361:in `instance_eval'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/provider.rb:361:in `compile_and_converge_action'
       (eval):2:in `action_create'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/provider.rb:145:in `run_action'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/resource.rb:603:in `run_action'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/runner.rb:69:in `run_action'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/runner.rb:97:in `block (2 levels) in converge'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/runner.rb:97:in `each'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/runner.rb:97:in `block in converge'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/runner.rb:96:in `converge'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/client.rb:669:in `block in converge'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/client.rb:664:in `catch'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/client.rb:664:in `converge'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/client.rb:703:in `converge_and_save'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/client.rb:283:in `run'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/application.rb:302:in `block in fork_chef_client'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/application.rb:290:in `fork'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/application.rb:290:in `fork_chef_client'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/application.rb:255:in `block in run_chef_client'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/local_mode.rb:44:in `with_server_connectivity'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/application.rb:243:in `run_chef_client'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/application/client.rb:450:in `loop'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/application/client.rb:450:in `interval_run_chef_client'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/application/client.rb:434:in `run_application'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/application.rb:60:in `run'
       /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/bin/chef-client:26:in `<top (required)>'
       /opt/chef/bin/chef-client:54:in `load'
```

**Comment by zhefanlin** [comment] 2016-10-25 22:40
having the same error on version 4.1.0

**Comment by iennae** [comment] 2016-10-26 11:00
Yes, I'll tag this with a milestone when I have a fix for it. Thanks.

**Comment by docwhat** [comment] 2016-10-28 21:06
The `jenkins_slave_jnlp` resource sure has been having trouble.  Are there tests needed?

**Comment by iennae** [comment] 2016-11-03 06:37
Thanks to @HighwayofLife this should be fixed. Can you take a look and verify with cookbook 4.1.1? Thanks.

**Comment by jmaass** [comment] 2016-11-03 09:38
Dear Jennifer,

I get a new error:

         * jenkins_jnlp_slave[192.168.211.134] action create
         Recipe: <Dynamically Defined Resource>
           * remote_file[/tmp/kitchen/cache/jenkins-cli.jar] action create
             - create new file /tmp/kitchen/cache/jenkins-cli.jar
             - update content in file /tmp/kitchen/cache/jenkins-cli.jar from none to 532e02
             (new content is binary, diff output suppressed)
             - change mode from '' to '0755'
             - restore selinux security context
           * remote_file[/tmp/kitchen/cache/update-center.json] action create
             - create new file /tmp/kitchen/cache/update-center.json
             - update content in file /tmp/kitchen/cache/update-center.json from none to ef855c
             - suppressed sensitive resource
             - change mode from '' to '0644'
             - restore selinux security context
           * file[/tmp/kitchen/cache/extracted-update-center.json] action create
             - create new file /tmp/kitchen/cache/extracted-update-center.json
             - update content in file /tmp/kitchen/cache/extracted-update-center.json from none to 080150
             - suppressed sensitive resource
             - change mode from '' to '0644'
             - restore selinux security context
           * file[/tmp/kitchen/cache/jenkins-key] action create
             - create new file /tmp/kitchen/cache/jenkins-key
             - update content in file /tmp/kitchen/cache/jenkins-key from none to 33300f
             - suppressed sensitive resource
             - change mode from '' to '0600'
             - restore selinux security context
           - Create jenkins_jnlp_slave[192.168.211.134]
           * directory[/home/jenkins] action create
             - create new directory /home/jenkins
             - restore selinux security context
           * group[jenkins] action create (up to date)
           * linux_user[jenkins] action create
             - alter user jenkins
           * directory[/home/jenkins] action create
             - change owner from 'root' to 'jenkins'
             - change group from 'root' to 'jenkins'
             - restore selinux security context
           * remote_file[/home/jenkins/slave.jar] action create
             - create new file /home/jenkins/slave.jar
             - update content in file /home/jenkins/slave.jar from none to f11c0b
             (new content is binary, diff output suppressed)
             - change mode from '' to '0755'
             - restore selinux security context

           ================================================================================
           Error executing action `create` on resource 'jenkins_jnlp_slave[192.168.211.134]'
           ================================================================================

           NoMethodError
           -------------
           undefined method `java' for Chef::Resource::RunitService

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/jenkins/libraries/slave_jnlp.rb:237:in `block in service_resource'
           /tmp/kitchen/cache/cookbooks/jenkins/libraries/slave_jnlp.rb:231:in `service_resource'
           /tmp/kitchen/cache/cookbooks/jenkins/libraries/slave_jnlp.rb:69:in `block in <class:JenkinsJnlpSlave>'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels)                                                                                                                                            in converge'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge                                                                                                                                           '
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/mnet_jenkins/recipes/slave.rb

            70: jenkins_jnlp_slave ipaddress do
            71:   remote_fs '/home/jenkins'
            72:   action [:create, :connect]
            73:   not_if { master == 'localhost' }
            74: end

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/mnet_jenkins/recipes/slave.rb:70:in `from_file'

           jenkins_jnlp_slave("192.168.211.134") do
             action [:create, :connect]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :jenkins_jnlp_slave
             cookbook_name "mnet_jenkins"
             recipe_name "slave"
             remote_fs "/home/jenkins"
             slave_name "192.168.211.134"
             usage_mode "normal"
             description "Jenkins slave 192.168.211.134"
             group "jenkins"
             user "jenkins"
             service_name "jenkins-slave"
             not_if { #code block }
           end

           Platform:
           ---------
           x86_64-linux

       Recipe: chef-client::systemd_service
         * service[chef-client] action restart
           - restart service service[chef-client]
       Recipe: misc::hosts_entry
         * service[network] action restart
           - restart service service[network]

       Running handlers:
       [2016-11-03T10:27:56+01:00] ERROR: Running exception handlers
       Running handlers complete
       [2016-11-03T10:27:56+01:00] ERROR: Exception handlers complete
       Chef Client failed. 58 resources updated in 45 seconds
       [2016-11-03T10:27:56+01:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2016-11-03T10:27:56+01:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2016-11-03T10:27:56+01:00] ERROR: jenkins_jnlp_slave[192.168.211.134] (mnet_jenkins::slave line 70) had an error: NoMethodEr                                                                                                                                           ror: undefined method `java' for Chef::Resource::RunitService
       [2016-11-03T10:27:56+01:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

The relying on runit and packagecloud is an error IMHO anyways. We, for example, pull our packages from the vendor repo and then use the startup mechanism the OS offers, in case of CentOS 7: systemd. While I know there is a religious debate going on about the feasibility of system, I frankly don’t give a damn from an operational perspective. We need to get the stuff to WORK, and if the OS offers a suitable startup method such as system, it will and should be used.

Unfortunately, our organization has not yet signed a CLA, so we can’t change the code ourselves, but we would highly appreciate it if you guys did.

I would therefore much appreciate it if the cookbook could be altered in such a way as to get rid of runit and switch to systemd on Linuxes of the RedHat family.

Mit freundlichen Grüßen/Kind regards

Jörg Maaß
Hays AG
Release Management Retail im Bereich IT
--
M-net Telekommunikations GmbH
Emmy-Noether-Str. 2 | 80992 München

Tel. 089 45200 8356 | Fax 089 45200 708356 | Mobil 0178 5352364
www.m-net.de<http://www.m-net.de/> | joerg.maass.ext@m-net.de<mailto:joerg.maass.ext@m-net.de>
M-net auf Facebook<http://www.facebook.com/Mnet.MeinNetz> | YouTube<http://www.youtube.com/user/MnetMeinNetz> | XING<http://www.xing.com/company/m-net>
Sitz München – Amtsgericht München HRB 108514
Geschäftsführer: Jens Prautzsch (Vorsitzender) | Simone Büber-Monath | Michael Fränkle
Vorsitzende des Aufsichtsrats: Erna-Maria Trixl
[M-net_Testsieger]

Von: Jennifer Davis [mailto:notifications@github.com]
Gesendet: Donnerstag, 3. November 2016 07:37
An: chef-cookbooks/jenkins
Cc: Maaß.Jörg; Author
Betreff: Re: [chef-cookbooks/jenkins] jenkins_jnlp_slave fails with undefined method (#531)


Thanks to @HighwayofLife<https://github.com/HighwayofLife> this should be fixed. Can you take a look and verify with cookbook 4.1.1? Thanks.

**Comment by iennae** [comment] 2016-11-03 13:53
We definitely plan to move away towards using system provided init systems like systemd for RHEL and Ubuntu, but that's a longer plan strategy. Can you open up a new issue for this error that you are receiving? There are a lot of issues with this cookbook that we're slowly unwinding, some of them dependent on each other but it's good to see some progress. Thanks so much.

**Comment by HighwayofLife** [comment] 2016-11-03 14:46
I can fix these errors as well. I suspected that theses errors could exist
but didn't experience them myself.

**Comment by docwhat** [comment] 2016-11-03 15:16
@HighwayofLife: #535 fixes the remaining items. I've been using this in our system for the past 6 days with no (obvious) issues.

**Closed** 2016-11-03 23:12 UTC

**Comment by sethrosenblum** [comment] 2016-11-04 16:36
This works for me during normal client runs but hangs during provision.  I get this error when I finally kill the process:
```
  Recipe: <Dynamically Defined Resource>
    * remote_file[/var/chef/cache/jenkins-cli.jar] action create (up to date)
    * remote_file[/var/chef/cache/update-center.json] action create (up to date)
    * file[/var/chef/cache/extracted-update-center.json] action create (up to date)
    * file[/var/chef/cache/jenkins-key] action create (up to date)
    * directory[/mnt/jenkins] action create (up to date)
    * group[jenkins] action create (up to date)
    * linux_user[jenkins] action create (up to date)
    * directory[/mnt/jenkins] action create (up to date)
    * remote_file[/mnt/jenkins/slave.jar] action create (up to date)
    * runit_service[jenkins-slave] action enable
      * ruby_block[restart_service] action nothing (skipped due to action :nothing)
      * ruby_block[restart_log_service] action nothing (skipped due to action :nothing)
      * directory[/etc/sv/jenkins-slave] action create (up to date)
      * template[/etc/sv/jenkins-slave/run] action create (up to date)
      * directory[/etc/sv/jenkins-slave/log] action create (up to date)
      * directory[/etc/sv/jenkins-slave/log/main] action create (up to date)
      * directory[/var/log/jenkins-slave] action create (up to date)
      * template[/etc/sv/jenkins-slave/log/config] action create (up to date)
      * link[/var/log/jenkins-slave/config] action create (up to date)
      * template[/etc/sv/jenkins-slave/log/run] action create (up to date)
      * directory[/etc/sv/jenkins-slave/env] action create (up to date)
      * ruby_block[zap extra env files for jenkins-slave service] action run (skipped due to only_if)
      * template[/etc/sv/jenkins-slave/check] action create (skipped due to only_if)
      * template[/etc/sv/jenkins-slave/finish] action create (skipped due to only_if)
      * directory[/etc/sv/jenkins-slave/control] action create (up to date)
      * link[/etc/init.d/jenkins-slave] action create (up to date)
      * file[/etc/sv/jenkins-slave/down] action nothing (skipped due to action :nothing)
      * directory[/etc/service] action create (up to date)
      * link[/etc/service/jenkins-slave] action create (up to date)
      * ruby_block[wait for jenkins-slave service socket] action run^C
        
        ================================================================================
        Error executing action `run` on resource 'ruby_block[wait for jenkins-slave service socket]'
        ================================================================================
        
        SystemExit
        ----------
        exit
        
        Cookbook Trace:
        ---------------
        /var/chef/cache/cookbooks/runit/libraries/helpers.rb:79:in `sleep'
        /var/chef/cache/cookbooks/runit/libraries/helpers.rb:79:in `wait_for_service'
        /var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:291:in `block (3 levels) in <class:RunitService>'
        /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
        /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
        /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
        /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
        /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
        /var/chef/cache/cookbooks/jenkins/libraries/slave_jnlp.rb:69:in `block in <class:JenkinsJnlpSlave>'
        /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
        /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
        /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
        /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
        /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
        
        Resource Declaration:
        ---------------------
        # In /var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb
        
        289:         ruby_block "wait for #{new_resource.service_name} service socket" do
        290:           block do
        291:             wait_for_service
        292:           end
        293:           action :run
        294:         end
        295: 
        
        Compiled Resource:
        ------------------
        # Declared in /var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:289:in `block in <class:RunitService>'
        
        ruby_block("wait for jenkins-slave service socket") do
          action [:run]
          retries 0
          retry_delay 2
          default_guard_interpreter :default
          block_name "wait for jenkins-slave service socket"
          declared_type :ruby_block
          cookbook_name "dd-jenkins"
          block #<Proc:0x000000059e3c70@/var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:290>
        end
        
        Platform:
        ---------
        x86_64-linux
        
```

I also noticed this when I investigated the host that it was hanging on:
```
$ sv
The program 'sv' is currently not installed. To run 'sv' please ask your administrator to install the package 'runit'
```

So, I don't think the `include_recipe 'runit'` in service_resource is getting called in time to install runit.

**Comment by sethrosenblum** [comment] 2016-11-04 17:09
I can confirm that this issue is fixed by adding `include_recipe 'runit'` immediately before `jenkins_jnlp_slave` in my cookbook.

Jenkins cookbook 4.1.2
Runit cookbook 1.8.0 & 3.0.0
Chef-client version 12.15.19

**Comment by iennae** [comment] 2016-11-04 18:50
Hi @sethrosenblum Can you create a new issue for this? Thanks.
