### ISSUE TITLE
Installing LDAP plugin fails to install dependencies correctly

### ISSUE THREAD

**Issue by CGreenburg** [chef-cookbooks/jenkins#627] opened 2017-06-14 20:40 UTC
### Cookbook version
5.0.1

### Chef-client version
Version installed on Test Kitchen instance:
- chef-client 13.1.31

### Platform Details
Test Kitchen
- Driver: Vagrant,
- Platform: ubuntu-16.04
- Provisioner: chef_zero

### Scenario:
```ruby
jenkins_plugin 'ldap' do
    notifies :restart, 'service[jenkins]', :immediately
end
```
The block of code above should install the following dependency chain:
`ldap(v1.15) -> mailer(v1.20) -> display-url-api(v1.0) -> junit(v1.3)`
display-url-api 2.0 removes the dependency on junit, however display-url-api 1.0 still requires it. The error I get is shown in the screen snippet below:
![screen shot 2017-06-13 at 2 05 56 pm](https://user-images.githubusercontent.com/13036301/27153280-7ef55572-5116-11e7-94aa-9d2d591f78e7.png)

### Steps to Reproduce:
Paste the block of code shown under scenario and when going to the UI, you should see the same as shown in my screen snippet under the notification menu.

### Expected Result:
I assume this is a bug and junit should get installed, right?

### Actual Result:
None of the plugins get enabled due to a dependency error.

**Comment by CGreenburg** [comment] 2017-06-14 20:44
I should note that the following code block fixes the problem, but figured I should put in a ticket anyway since I think this is unexpected behavior.

```ruby
jenkins_plugin 'junit'
jenkins_plugin 'ldap' do
    notifies :restart, 'service[jenkins]', :immediately
end
```

**Comment by ehaselwanter** [comment] 2017-06-15 09:10
have a look at https://github.com/chef-cookbooks/jenkins/issues/534#issuecomment-259629933
(the whole thread might be interesting for you)

**Comment by tas50** [comment] 2017-07-04 19:28
Closing this as it's a duplicate of #534. It's a tough one to solve and we're going to have to dig in and figure out something

**Closed by tas50** 2017-07-04 19:28 UTC
