### ISSUE TITLE
Can not install Jenkins 2.x release other than the latest version

### ISSUE THREAD

**Issue by fawzyj** [chef-cookbooks/jenkins#482] opened 2016-06-06 17:31 UTC
### Cookbook version

2.5
### Chef-client version

12.9.38
### Platform Details

Ubuntu 14.04
### Scenario:

Can not install Jenkins 2.x release other than the latest
For example, currently the 2.x release is 2.8, so if i set the attribute node[:jenkins][:master][:version] = 2.8 it works fine, but if the value is 2.7 , or 2.6... etc it fails with the following message

STDERR: E: Version '2.7' for 'jenkins' was not found
==> default: ---- End output of apt-get -q -y install jenkins=2.7 ----
==> default: Ran apt-get -q -y install jenkins=2.7 returned 100

So, I am able to install the latest version, but when jenkins release new one, my version attribute do not point to the latest version anymore, so my chef run fails
### Steps to Reproduce:

[If you are filing an issue what are the things we need to do in order to repro your problem? How are you using this cookbook or any resources it includes?]
### Actual Result:

On Ubuntu machine, , set node[:jenkins][:master][:version] = 2.7, it will fail to install that version,
change the value to 2.8 (or whatever latest version on test time is) and it will install jenkins

**Comment by Chili-Man** [comment] 2016-06-06 19:06
Since it seems that you're installing it via an apt package, the  apt repos for jenkins will only have the latest version available thus  it can never respect the version set in the attributes. You have to install jenkins via the `war` method by setting:

```
node.set['jenkins']['master']['install_method'] = 'war'
```

then it will respect the version you specify in the attributes.

**Comment by davidcpell** [comment] 2016-08-11 19:18
@Chili-Man I've been trying this with `1.653` because the current cookbook seems to have trouble with Jenkins 2, but even with that set and the `install_method` changed to `war`, I'm still getting version 2.17 of Jenkins

**Comment by JoeNunnelley** [comment] 2016-08-18 20:51
i am hitting this issue as well. I would like to continue to install 1.653 with my chef runs but its failing to find it even when I set the 'source' attribute and point it at the mirror for the 1.653 war file.  It still just install 2.18 which is the latest on that mirror.  Is there some configuration for the chef attributes I"m missing?

```
default['jenkins']['master']['install_method'] = 'war'
default['jenkins']['master']['version'] = '1.651.3'
default['jenkins']['master']['source'] = 'http://mirrors.jenkins-ci.org/war/1.653/jenkins.war'
```

**Comment by davidcpell** [comment] 2016-08-18 22:37
@JoeNunnelley as odd as it sounds, I was able to force the install of `v1.651.3` by *only* setting the `source` attribute and *not* the version. It looks like this in my `attributes/default.rb`:

```
default['jenkins']['master'].tap do |master|
  master['install_method'] = 'war'
  master['source'] = 'http://mirrors.jenkins-ci.org/war-stable/1.651.3/jenkins.war'
end
```

**Comment by lioramilbaum** [comment] 2016-12-08 03:58
+1

**Comment by tradenity** [comment] 2016-12-08 15:26
@davidcpell sure you can, We are talking about version 2.x
The issue is that the apt repo have all 1.x.x versions, but only the latest 2.x release

**Comment by lioramilbaum** [comment] 2016-12-08 15:31
@tradenity apt repo have only the latest 2.x release (now it is 2.35). I wanted to install 2.34. It didn't work when used the package install method. Did work as @davidcpell specified.

**Comment by tradenity** [comment] 2016-12-08 15:42
That's what I'm saying... you can install any 1.x version via apt, but only the latest 2.x

**Comment by lioramilbaum** [comment] 2016-12-08 15:44
ok. Wasn't sure I understood you.
Who is responsible for updating the apt repos?

**Comment by cheeseplus** [comment] 2016-12-23 05:26
This particular issue has to do with the upstream Jenkins repos themselves and not really anything to do with the cookbook itself, as such closing.

**Closed by cheeseplus** 2016-12-23 05:26 UTC

**Comment by olgafandeliuk** [comment] 2020-09-24 13:56
> @JoeNunnelley I was able to force the install of `v1.651.3` by _only_ setting the `source` and `install_method` attributes and _not_ the version. The relevant part of my `attributes/default.rb` looks like this:
> 
> ```
> default['jenkins']['master'].tap do |master|
>   master['install_method'] = 'war'
>   master['source'] = 'http://mirrors.jenkins-ci.org/war-stable/1.651.3/jenkins.war'
> end
> ```

Thank you for your tip! It really helps us to pin jenkins-master version=)
