### ISSUE TITLE
Can't modify frozen jenkins_jnlp_slave

### ISSUE THREAD

**Issue by cheesesashimi** [chef-cookbooks/jenkins#615] opened 2017-05-12 17:32 UTC
### Cookbook version
v5.0.1

### Chef-client version
13.0.118

### Platform Details
Chef Client is running in a Vagrant VM driven by Test Kitchen. VM is a Centos 7.2 machine provided by Bento (`bento/centos-7.2`). My development machine is a Macbook Pro running macOS 10.12.3 with the following ChefDK:

```shell
$ chef --version
Chef Development Kit Version: 1.3.43
chef-client version: 12.19.36
delivery version: master (dd319aa632c2f550c92a2172b9d1226478fea997)
berks version: 5.6.4
kitchen version: 1.16.0
```

### Scenario:
I'm trying to create a new Jenkins slave by leveraging the `jenkins_jnlp_slave` resource. Whenever my cookbook converges, it appears to create the slave and set it up correctly. I can verify this by going into the Jenkins master I'm testing against and finding my test VM connected and ready. I'm even able to schedule Jenkins jobs to run on it. Despite the slave being functional, the Chef Client run fails. I've included the error message in the Actual Results section.

### Steps to Reproduce:
Initially, I thought the issue was due to my usage of the `jenkins_jnlp_slave` resource, so I created a test cookbook which you can find [here]( https://github.com/cheesesashimi/jenkins_jnlp_test_cookbook). Using that cookbook, one can reproduce the issue simply by running: `$ kitchen converge`.

However, I discovered this morning the issue may be reproduced without my test cookbook. Simply clone this repo and run the following test suite:

`$ kitchen converge jenkins-slave-create-centos-73`

### Expected Result:
In the case of my test cookbook, I was expecting Chef Client to complete its run successfully. In the case of the `jenkins_slave_create` test cases, I was expecting the cookbook to converge correctly and for Test Kitchen to run the verifier.

### Actual Result:

This is the error message I got from trying to run the `jenkins_slave_create` test suite:
```
================================================================================
Error executing action `create` on resource 'jenkins_jnlp_slave[builder]'
================================================================================

RuntimeError
------------
can't modify frozen #<Class:#<Chef::Resource::JenkinsJnlpSlave:0x00000004bb4d48>>

Resource Declaration:
---------------------
# In /tmp/kitchen/cache/cookbooks/jenkins_slave/recipes/create_jnlp.rb

   10: jenkins_jnlp_slave 'builder' do
   11:   description  'A generic slave builder'
   12:   remote_fs    '/tmp/jenkins/slaves/builder'
   13:   service_name 'jenkins-slave-builder'
   14:   labels       %w(builder linux)
   15:   user         'jenkins-builder'
   16:   group        'jenkins-builder'
   17: end
   18:

Compiled Resource:
------------------
# Declared in /tmp/kitchen/cache/cookbooks/jenkins_slave/recipes/create_jnlp.rb:10:in `from_file'

jenkins_jnlp_slave("builder") do
   action [:create]
   default_guard_interpreter :default
   declared_type :jenkins_jnlp_slave
   cookbook_name "jenkins_slave"
   recipe_name "create_jnlp"
   description "A generic slave builder"
   remote_fs "/tmp/jenkins/slaves/builder"
   service_name "jenkins-slave-builder"
   labels ["builder", "linux"]
   user "jenkins-builder"
   group "jenkins-builder"
   slave_name "builder"
end

System Info:
------------
chef_version=13.0.118
platform=centos
platform_version=7.3.1611
ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
program_name=chef-client worker: ppid=3797;start=17:23:59;
executable=/opt/chef/bin/chef-client

Recipe: jenkins::_master_war
* runit_service[jenkins] action restart (up to date)

Running handlers:
[2017-05-12T17:28:59+00:00] ERROR: Running exception handlers
[2017-05-12T17:28:59+00:00] ERROR: Running exception handlers
Running handlers complete
[2017-05-12T17:28:59+00:00] ERROR: Exception handlers complete
[2017-05-12T17:28:59+00:00] ERROR: Exception handlers complete
Chef Client failed. 74 resources updated in 05 minutes 00 seconds
[2017-05-12T17:28:59+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
[2017-05-12T17:28:59+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
[2017-05-12T17:28:59+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2017-05-12T17:28:59+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2017-05-12T17:28:59+00:00] ERROR: can't modify frozen #<Class:#<Chef::Resource::JenkinsJnlpSlave:0x00000004bb4d48>>
[2017-05-12T17:28:59+00:00] ERROR: can't modify frozen #<Class:#<Chef::Resource::JenkinsJnlpSlave:0x00000004bb4d48>>
[2017-05-12T17:28:59+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
[2017-05-12T17:28:59+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

### Misc.:
I observed in https://github.com/chef-cookbooks/jenkins/issues/537 that the CI testing for this repo omits the aforementioned test suites.

I'm happy to provide additional information / testing if needed.

**Comment by cheesesashimi** [comment] 2017-05-13 01:42
At someone's suggestion, I did some more cogitation / testing and I came to the following conclusion:

Pinning Chef Client to 12.19.36, this resource ran with no trouble. With that in mind and given that Chef 13 was released very recently and introduces a number of [breaking changes](https://docs.chef.io/release_notes.html), this resource (and possibly others) are broken in Chef 13. I happened to encounter this because my Chef-generated `.kitchen.yml` does not pin the Chef Client version. That said, if something breaks, test-kitchen is the best place for that to happen :smile:.

I also realize I neglected to include my chef-stacktrace.out file when I created this issue. It can be found [here](https://github.com/chef-cookbooks/jenkins/files/998258/chef-stacktrace.out.txt).

**Comment by lioramilbaum** [comment] 2017-08-08 22:33
+1

**Comment by oberones** [comment] 2017-11-01 18:38
I am also encountering this problem since upgrading to Chef 13, but going to back to Chef 12.x isn't an option for us at this point. Has anyone been able to make any progress in isolating the cause of this?

**Comment by tas50** [comment] 2017-11-23 00:00
This has been fixed on master and I'll be cutting a release once I fix a few other problems

**Closed by tas50** 2017-11-23 00:00 UTC
