### ISSUE TITLE
undefined method `[]' for nil:NilClass for bouncycastle-api plugin that should exist.

### ISSUE THREAD

**Issue by coltrey** [chef-cookbooks/jenkins#623] opened 2017-06-07 20:01 UTC
I'm encountering this error on a plugin that should exist.  This worked May 23, but fails today.  I have not changed any cookbook code, nor the version of the jenkins/chef cookbook - not sure where to look.  Update center on an existing instance shows this plugin and version, and I can see the plugin and version in https://updates.jenkins.io/current/update-center.json as well as go to the url specified (http://updates.jenkins-ci.org/download/plugins/bouncycastle-api/2.16.1/bouncycastle-api.hpi) and download the plugin manually.  This step also retried 4 times to deal with transient network issues.

```
================================================================================
Error executing action `install` on resource 'jenkins_plugin[bouncycastle-api]'
================================================================================

NoMethodError
-------------
undefined method `[]' for nil:NilClass

Cookbook Trace:
---------------
/var/chef/runs/d9cc7b8f-06a3-4c18-8b70-b7394b56b6e3/local-mode-cache/cache/cookbooks/jenkins/libraries/plugin.rb:267:in `install_plugin_from_update_center'
/var/chef/runs/d9cc7b8f-06a3-4c18-8b70-b7394b56b6e3/local-mode-cache/cache/cookbooks/jenkins/libraries/plugin.rb:124:in `block (2 levels) in <class:JenkinsPlugin>'
/var/chef/runs/d9cc7b8f-06a3-4c18-8b70-b7394b56b6e3/local-mode-cache/cache/cookbooks/jenkins/libraries/plugin.rb:154:in `block in <class:JenkinsPlugin>'

Resource Declaration:
---------------------
# In /var/chef/runs/d9cc7b8f-06a3-4c18-8b70-b7394b56b6e3/local-mode-cache/cache/cookbooks/JenkinsConfiguration/recipes/install.rb

 32:   jenkins_plugin pluginName do
 33:     version versionNumber
 34:     install_deps false
 35:     retries 4
 36:     retry_delay 15
 37:   end
 38: end

Compiled Resource:
------------------
# Declared in /var/chef/runs/d9cc7b8f-06a3-4c18-8b70-b7394b56b6e3/local-mode-cache/cache/cookbooks/JenkinsConfiguration/recipes/install.rb:32:in `plugin'

jenkins_plugin("bouncycastle-api") do
  action [:install]
  retries 4
  retry_delay 15
  default_guard_interpreter :default
  declared_type :jenkins_plugin
  cookbook_name "JenkinsConfiguration"
  recipe_name "install"
  version "2.16.1"
end

Platform:
---------
x86_64-linux

```

### Cookbook version
5.0.1

### Chef-client version
aws opsworks

### Platform Details
aws opsworks

### Scenario:
install bouncycastle-api plugin

### Steps to Reproduce:
```
jenkins_plugin("bouncycastle-api") do
  action [:install]
  retries 4
  retry_delay 15
  default_guard_interpreter :default
  declared_type :jenkins_plugin
  cookbook_name "JenkinsConfiguration"
  recipe_name "install"
  version "2.16.1"
end

```
### Expected Result:
plugin installed

### Actual Result:
[What actually happens after the reproduction steps? Include the error output or a link to a gist if possible.]

**Comment by MooreDerek** [comment] 2017-06-07 21:08
I'm seeing the same behaviour with the following plugin `display-url-api`.  I've checked the chef cache 'update-center.json` on the server I'm trying to update and the plugin is not listed. However, if I check the output from `wget -O default.json http://updates.jenkins-ci.org/update-center.json`, the plugin is definitely there.
Suspect that the plugins are missing from the update center but can't confirmed which one the recipe is using.  

The contents of the `$JENKINS-HOME/hudson.model.UpdateCenter.xml` on the Jenkins server is:
```
<?xml version='1.0' encoding='UTF-8'?>
<sites>
  <site>
    <id>default</id>
    <url>http://updates.jenkins-ci.org/update-center.json</url>
  </site>
</sites>
```

**Comment by dshvedchenko** [comment] 2017-06-08 07:09
Hello,
Looks like some changes at UpdateCenter:
with combination of default value node['jenkins']['master']['channel'] == 'stable'
now https://updates.jenkins.io/stable/update-center.json redirects to https://updates.jenkins.io/stable-1.580/update-center.json , which does not contain required plugins

to fix: I've altered node['jenkins']['master']['channel'] = 'stable-2.46' for LTS in wrapper cookbook

**Comment by ramereth** [comment] 2017-06-08 21:13
This seems to be related to this: https://issues.jenkins-ci.org/browse/INFRA-1215

**Comment by daniel-beck** [comment] 2017-06-08 22:30
Should be fixed. Sorry about that.

**Comment by MooreDerek** [comment] 2017-06-09 01:28
This is now working for us, with the change for INFRA-1215.

**Comment by tas50** [comment] 2017-07-04 19:29
Closing this out since it looks like it's been resolved

**Closed** 2017-07-04 19:29 UTC
