### ISSUE TITLE
jenkins_plugin resource is really inefficient and installs incompatible dependencies

### ISSUE THREAD

**Issue by daytonpa** [chef-cookbooks/jenkins#653] opened 2017-08-23 15:38 UTC
### Cookbook version
5.0.3

### Chef-client version
```
Chef Development Kit Version: 2.1.11
chef-client version: 13.2.20
delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
berks version: 6.3.0
kitchen version: 1.17.0
inspec version: 1.33.1
```

### Platform Details
Ubuntu 16.04

### Scenario:
Install basic plugins and their dependencies for a Jenkins-based pipeline.

### Steps to Reproduce:
Use recipe and attributes included at base of this Issue.

### Expected Result:
Have Chef idempotently check plugin installations as well as their recommended dependencies without raising warnings on the Dashboard.

### Actual Result:
Chef spent half an hour going through every plugin and installing plugin dependencies that were incompatible.  Raised multiple warnings in the Jenkins Dashboard.
```
Running handlers:
       Running handlers complete
       Chef Client finished, 212/1034 resources updated in 29 minutes 42 seconds
       Finished converging <default-ubuntu-1604> (30m25.87s).
```

##### Recipe used:
```
# Create/verify we have a directory to place our desired plugins
directory node['docnetwork-scruffy']['home'] + '/plugins' do
  owner node['docnetwork-scruffy']['user']
  group node['docnetwork-scruffy']['group']
  mode '0755'
end

# Download and install our desired plugins and their dependencies
node['docnetwork-pipeline']['plugins'].tap do |plugins|
  plugins['default'].each do |plugin|
    jenkins_plugin plugin do
      install_deps true
      notifies :restart, 'service[jenkins]', :delayed
    end
  end
  plugins['security'].each do |plugin|
    jenkins_plugin plugin do
      install_deps true
      notifies :restart, 'service[jenkins]', :delayed
    end
  end
  plugins['because_I_said_so'].each do |plugin|
    jenkins_plugin plugin do
      install_deps true
      notifies :restart, 'service[jenkins]', :delayed
    end
  end
end
```
##### Attributes used:
```
default['docnetwork-pipeline']['plugins'].tap do |plugins|
  plugins['default'] = %w(
    scm-api
    git
    git-client
    github-api
    github
    chef-identity
  )
  # Security-based plugins
  plugins['security'] = %w(
    matrix-auth
  )
  plugins['because_I_said_so'] = %w(
    chucknorris
  )
end
```
##### Output from converge:
I uploaded a file into my google drive [here](https://docs.google.com/document/d/1O1QEgEoXuJGfwjFt6Oy4idB7oN0ujeo_VYtBLgjX-h4/edit?usp=sharing).  It's only from that recipe above, and it's a big one!

##### Jenkins Dashboard:
![screenshot from 2017-08-23 11-31-09](https://user-images.githubusercontent.com/18060246/29624302-b85428f4-87f6-11e7-935b-fcdbafa8a9e7.png)

**Comment by cgianelloni-applause** [comment] 2017-08-25 19:49
You're lucky. My plugin list is taking about 2 hours to even converge (and there aren't that many, really)...

**Comment by john-miller** [comment] 2017-08-25 20:51
Got burned by this too -- Github OAuth plugin wasn't installing causing major problems for me.  Found managing the plugins and versions is a little more predictable and less time consuming.  Here's what I got to work but don't give me credit, I stole this from someone here. 

```
plugins = {
  'credentials'              => '2.1.14',
  'plain-credentials'        => '1.1',
  'token-macro'              => '1.11',
  'ace-editor'               => '1.0.1',
  'branch-api'               => '2.0.7',
  'cloudbees-folder'         => '5.18',
  'jquery-detached'          => '1.2.1',
  'jackson2-api'             => '2.7.3',
  'display-url-api'          => '1.0',
  'mailer'                   => '1.20',
  'ssh-credentials'          => '1.13',
  'scm-api'                  => '2.2.0',
  'structs'                  => '1.10',
  'git-client'               => '2.5.0',
  'git'                      => '3.5.1',
  'github'                   => '1.28.0',
  'workflow-api'             => '2.15',
  'workflow-aggregator'      => '2.1',
  'workflow-cps'             => '2.32',
  'workflow-job'             => '2.10',
  'workflow-scm-step'        => '2.4',
  'workflow-step-api'        => '2.10',
  'workflow-support'         => '2.14',
  'workflow-basic-steps'     => '2.3',
  'pipeline-input-step'       => '2.5',
  'workflow-durable-task-step' => '2.8',
  'workflow-cps-global-lib'  => '2.5',
  'pipeline-stage-view'       => '2.4',
  'pipeline-model-definition' => '1.0',
  'pipeline-stage-step'      => '2.2',
  'pipeline-build-step'      => '2.4',
  'pipeline-milestone-step'  => '1.3',
  'github-branch-source'     => '1.9',
  'github-api'               => '1.86',
  'workflow-multibranch'     => '2.9',
  'credentials-binding'      => '1.11',
  'docker-workflow'          => '1.9',
  'pipeline-model-api'       => '1.1.9',
  'pipeline-model-declarative-agent' => '1.1.1',
  'pipeline-model-extensions' => '1.1.9',
  'pipeline-stage-tags-metadata' => '1.1.9',
  'matrix-project'           => '1.7',
  'junit'                    => '1.20',
  'script-security'          => '1.13',
  'github-oauth'             => '0.27',
  'git-server'               => '1.7',
  'pipeline-rest-api'        => '2.8',
  'handlebars'               => '1.1',
  'momentjs'                 => '1.1',
  'durable-task'             => '1.14',
  'docker-commons'           => '1.5',
  'pipeline-graph-analysis'  => '1.1',
  'icon-shim'                => '1.0.3',
  'authentication-tokens'    => '1.1'
}

plugins.each_with_index do |(plugin_name, plugin_version), index|
  jenkins_plugin plugin_name do
    action  :install
    install_deps false
    # only restart on the final plugin
    if index == (plugins.size - 1)
      notifies :restart, 'service[jenkins]', :immediately
    end
  end
end
```

**Comment by daytonpa** [comment] 2017-08-25 20:58
Haha I did the exact same thing.  It's a pain to fix the dependency erros as you install plugins, but it works.

**Comment by jharshman** [comment] 2017-08-31 00:26
+1 - running into this too. Same workaround as above but it's a pain to maintain.

**Comment by StephenKing** [comment] 2017-08-31 04:41
Duplicate of #534

**Comment by sjmiller609** [comment] 2018-08-03 15:10
Thank you @john-miller for your post. Is it possible that if you later update your versions, and the last plugin is not updated, then service[jenkins] will not be notified? I will leave this snippet here for others to consider.
`
plugins.each do | name, plug_version |
  jenkins_plugin name do
      version plug_version
      action :install
      install_deps false
      # if network hiccups, re-try in 5 seconds
      retries 3
      retry_delay 5
      notifies :touch, 'file[/update_occured]', :immediately
  end
end

jenkins_command 'quiet-down -block' do
  retries 10
  retry_delay 6
  only_if "test -f /update_occured"
end

service "jenkins" do
  action :stop
  only_if "test -f /update_occured"
end

# specific for my use case
service "docker" do
  action :restart
  only_if "test -f /update_occured"
end

service "jenkins" do
  action :start
  only_if "test -f /update_occured"
end

file "/update_occured" do
  action :delete
end
`

**Comment by gerardborst** [comment] 2018-09-17 15:06
Hi,

I don't know anything about Chef, I was trying to find something else, but are you aware there are standard solutions for your issues? This one is a shell script for building a Jenkins Docker image which does exactly what is asked https://github.com/jenkinsci/docker/blob/master/install-plugins.sh.

**Closed** 2020-07-14 16:25 UTC
